<h1>Problema 1 Parte 2</h1>
<form class="form-inline" id="frmrange" name="frmrange" method="post" action="<?php echo $this->basePath('application/completerange/rangeval');?>">
  <div class="form-group">
    <label class="sr-only" for="Cadena">Ingrese Rango [2,3,4,5]:</label>
    <input type="text" class="form-control" id="txtcadena" name="txtcadena" value="55,58,60">
    
  </div><br>

  <button type="submit" class="btn btn-default">Procesar</button>
  <button type="reset" class="btn btn-default">Nuevo</button>
</form>