<h1>Problema 1 Parte 3</h1>
<form class="form-inline" id="frmrange" name="frmrange" method="post" action="<?php echo $this->basePath('application/clearpar/paresval');?>">
  <div class="form-group">
    <label class="sr-only" for="Cadena">Ingrese Elementos pares:</label>
    <input type="text" class="form-control" id="txtcadena" name="txtcadena" value="()())()">
    
  </div><br>

  <button type="submit" class="btn btn-default">Procesar</button>
  <button type="reset" class="btn btn-default">Nuevo</button>
</form>