<h1>Problema 2/Web service</h1>
<form class="form-inline" id="frmrange" name="frmrange" method="post" action="<?php echo $this->basePath('application/webservice/query');?>">
  <div class="form-group">
    <label class="sr-only" for="Cadena">Salario de:</label>
    <input type="text" class="form-control" id="salarios1" name="salarios1" style="width:90px " value="1000">
    <label class="sr-only" for="Cadena">Hasta:</label>
    <input type="text" class="form-control" id="salarios2" name="salarios2" style="width:90px " value="1500">
    
  </div><br>

  <button type="submit" class="btn btn-default">Buscar</button>
  <button type="reset" class="btn btn-default">Nuevo</button>
</form>
<div>
  <table class="table table-inverse">
  <thead>
    <tr>
        <th>#</th>
        <th> name</th>
        <th> email</th>
        <th> salary</th>
        <th> position</th>        
    </tr>
  </thead>     
  <tbody>
      <?php
    $i=0;
       foreach ($this->data as $nodo) {

            $i++;
        $id = $nodo->id;
    ?> 
    <tr>      
      <th scope="row"><?php echo $i;?></th>
      <td><?php echo $nodo['name'];?></td>
      <td><?php echo $nodo->email;?></td>
      <td><?php echo "$".$nodo->salary;?></td>
      <td><?php echo $nodo->position;?></td>      
    </tr>
        <?php
        //}
      
    }
    ?>
  </tbody>
</table>    
    
</div>