<h1>Problema 1 Parte 1</h1>
<form class="form-inline" id="frmchangestring" name="frmchangestring" method="post" action="<?php echo $this->basePath('application/changestring/strval'); ?>">
  <div class="form-group">
    <label class="sr-only" for="Cadena">Ingrese Cadena:</label>
    <input type="text" class="form-control" id="txtcadena" name="txtcadena" value='"123 abcd*3"'>
  </div><br>

  <button type="submit" class="btn btn-default">Procesar</button>
  <button type="reset" class="btn btn-default">Nuevo</button>
</form>

